/* Generated by Together */

public class IfStat extends Statement {

  Expression cond;
  Statements truePart;
  ElseIfStats elseIfs;
  Statements falsePart;
  
  void setCond( Expression e ){ cond = e; }
  void setTruePart( Statements s ){ truePart = s; }
  void setElseIfStats( ElseIfStats e ){ elseIfs = e; }
  void setFalsePart( Statements s ){ falsePart = s; }
  public String toString(){
    String toString = "If Statement( " + cond.toString() + "){\n";
    if( truePart!=null ) toString+=truePart.toString();
    toString += "\n}";
    if( elseIfs != null )toString+=elseIfs.toString();
    toString+="else{\n" + falsePart.toString() + "\n}";
    return toString;
  }
  
  void typeCheck() throws TypeCheckException{
    cond.typeCheck();
    ensureBool(cond,"<If Stat>");
    truePart.typeCheck();
    elseIfs.typeCheck();
    if( falsePart != null )falsePart.typeCheck();
  }

  void genCode(){
    System.out.println(";-------------if--------------");
    String label1 = Cls.getLabel();
    String label2 = Cls.getLabel();
    cond.genCode();
    System.out.println( "ifeq " + label1 );
    truePart.genCode();
    System.out.println( "goto " + label2 );
    System.out.println( label1 + ":" );
    elseIfs.genCode( label2 );
    if( falsePart != null )falsePart.genCode();
    System.out.println( label2 + ":" );
    System.out.println(";-------------endif----------");
  }

  void genLoad(){ genCode(); }

}

