/* Generated by Together */
import java.util.Hashtable;
public class Qualifiers extends Hashtable{
  boolean isFinal(){ return get("final")!= null; }
  boolean isStatic(){ return get("static")!=null; }
  void addQualifier( String q ){ put( q,q ); }
  void genCode(){ 
    if( isStatic() ) System.out.print( "static " );
    if( isFinal() ) System.out.print( "final " );
  }
}
