/* Generated by Together */

public class Expression extends Statement{

  Cls type;
  
  public String toString(){ return "Expression()"; }
  
  void typeCheck() throws TypeCheckException {}
  
  Cls getType(){ return type; }
   
  void genCode(){
    System.out.println("Expression");
  }

  void genLoad(){
    System.out.println("LOAD");
  }
  
  void genStore(){
    System.out.println("STORE");
  }

}

