/* Generated by Together */

public class ExpStat extends Statement{

  Expression exp;
  
  ExpStat( Expression e ){ exp = e; }
  
  void setExp( Expression e ){ exp=e; }
  Expression getExp(){ return exp; }
  
  public String toString(){
    String toString="ExpStat: \n" + exp.toString();
    return toString;
  }
  
  void typeCheck() throws TypeCheckException{ 
    exp.typeCheck();
  }
  
  void genCode(){
    exp.genLoad();
    if( exp instanceof NewStatement ) System.out.println( "pop" );
  }

  void genLoad(){ genCode(); }

}
