/* Generated by Together */
import java.util.Iterator;

public class Mod extends BinaryExpression{

  ExpressionList el;
  
  Mod(){ el = new ExpressionList(); }
  
  void add( Expression e ){ el.add( e ); }
  
  public String toString() { 
    String toString = "ModStatement:\n";
    for( Iterator it = el.iterator(); it.hasNext(); ){
      toString += ((Expression)it.next()).toString();
      if( it.hasNext() ) toString += " <Mod> ";
    }
    return toString + "\n";
  }

  void typeCheck() throws TypeCheckException {
    el.typeCheck(); 
    type = Cls.INT;
    ensureSameTypes( el, "%" );
    ensureInt( el, "%" );
  }
    
}
