/* Generated by Together */

import java.util.Iterator;

public class Multiply extends BinaryExpression {
  
  Multiply(){ el = new ExpressionList(); }

  void add( Expression e ){ el.add( e ); }

  public String toString() { 
    String toString = "MultStatement:\n";
    for( Iterator it = el.iterator(); it.hasNext(); ){
      toString += ((Expression)it.next()).toString();
      if( it.hasNext() ) toString += " <Mult> ";
    }
    return toString + "\n";
  }

  void typeCheck() throws TypeCheckException {
    el.typeCheck(); 
    type = Cls.INT;
    ensureSameTypes( el, "*" );
    ensureInt( el, "*" );
  }  

  void genCode(){
    genLoads();
    genOperators( "imul" );
  }
}
