/* Generated by Together */
import java.util.ArrayList;
import java.util.Iterator;
public class Params extends ArrayList {

  public String toString(){
    if( this==null ) return "No Fields";
    String toString="\t\tParams:\n";
    for( Iterator it = this.iterator(); it.hasNext(); ){
      Param p = (Param)it.next();
      toString+= "\t\t\t" + p.toString() + "\n";
    }
    return toString;
  }

  void addParam( Param p ){
    if( ! contains( p ) ) add( p ); 
    else{ 
      System.out.println("Parameter: " + p.getName() + 
                         " already declared in Method: " + 
                         p.getScope().getName() + " " +
                         "Class: " + p.getScope().getScope().getName() ); 
    }
  }
    
  boolean contains( Var v ){
    for( Iterator it = iterator(); it.hasNext(); ){
      if( ((Param)it.next()).getName().equals( v.getName() ))  
        return true;
      }
    return false;
  }  
  
  Param get( String name ){
    for( Iterator it = this.iterator(); it.hasNext(); ){
      Param p = (Param)it.next();
      if( p.getName().equals( name ) ) return p;
    }
    return null;
  }
  
  void genCode() {
    if( this==null ) return;
    for( Iterator it = this.iterator(); it.hasNext(); ){
      Param p = (Param)it.next();
      p.genCode();
    }
  }
}
