/* Generated by Together */

public class CodeBody {
  Method env;
  Statements statements;
  
  CodeBody( Statements s, Method m ){ statements = s; env = m; }
  
  void setEnv( Method m ){ env = m; }
  void setStatements( Statements s ){ statements = s; }
  
  public String toString(){ return statements.toString(); }
  
  void typeCheck() throws TypeCheckException{
    statements.typeCheck();
  }
  
  void genCode(){
    statements.genCode();
  }
}
