/* Generated By:JavaCC: Do not edit this line. MODLParserConstants.java */
public interface MODLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int ANY = 9;
  int BOOL = 10;
  int CHAR = 11;
  int CHARLIT = 12;
  int CLASS = 13;
  int DO = 14;
  int ELSE = 15;
  int ELSEIF = 16;
  int EXTENDS = 17;
  int END = 18;
  int FALSE = 19;
  int FINAL = 20;
  int IF = 21;
  int INT = 22;
  int INTLIT = 23;
  int LOCAL = 24;
  int MAIN = 25;
  int NEW = 26;
  int NULL = 27;
  int OP = 28;
  int PRINT = 29;
  int RETURN = 30;
  int STATIC = 31;
  int THEN = 32;
  int THIS = 33;
  int TRUE = 34;
  int VAR = 35;
  int VOID = 36;
  int WHILE = 37;
  int INTEGER_LITERAL = 38;
  int CHARACTER_LITERAL = 39;
  int STRING_LITERAL = 40;
  int ASSIGN = 41;
  int GT = 42;
  int LT = 43;
  int EQ = 44;
  int LE = 45;
  int GE = 46;
  int NE = 47;
  int OR = 48;
  int AND = 49;
  int PLUS = 50;
  int MINUS = 51;
  int MULTIPLE = 52;
  int DIVIDE = 53;
  int MOD = 54;
  int NOT = 55;
  int COLON = 56;
  int DOT = 57;
  int COMMA = 58;
  int SEMI = 59;
  int LBRACKET = 60;
  int RBRACKET = 61;
  int IDENTIFIER = 62;
  int LETTER = 63;
  int DIGIT = 64;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"Any\"",
    "\"bool\"",
    "\"char\"",
    "\"charLit\"",
    "\"class\"",
    "\"do\"",
    "\"else\"",
    "\"elseif\"",
    "\"extends\"",
    "\"end\"",
    "\"false\"",
    "\"final\"",
    "\"if\"",
    "\"int\"",
    "\"intLit\"",
    "\"local\"",
    "\"main\"",
    "\"new\"",
    "\"null\"",
    "\"op\"",
    "\"PRINT\"",
    "\"return\"",
    "\"static\"",
    "\"then\"",
    "\"this\"",
    "\"true\"",
    "\"var\"",
    "\"void\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"|\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\":\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
