/* Generated by Together */

public class Negation extends UnaryExpression{
  
  Expression exp;
  
  public void setExpression(Expression e) { exp = e; }

  public String toString() { return "Negation Expression"; }
 
  void typeCheck() throws TypeCheckException {
    exp.typeCheck(); 
    type = Cls.INT;
    ensureInt( exp, "-" );
  }
  
 
  void genCode(){
    exp.genCode();
    System.out.println( "ineg" );
  }
  
  void genLoad(){
    genCode();
  }
}
