/* Generated by Together */

import java.util.LinkedList;
import java.util.Iterator;

public class Statements extends LinkedList{

  public String toString(){ 
    String toString="Statements:";
    for( Iterator it = this.iterator(); it.hasNext(); ){
      Statement s = (Statement)it.next();
      toString += "\n" + s.toString();
    }
    return toString;
  }
  
  void typeCheck() throws TypeCheckException{
    for( Iterator it = this.iterator(); it.hasNext(); ){
      Statement s = (Statement)it.next();
      try{
        s.typeCheck();
      } catch( TypeCheckException t ){
        CompilerSystem.addTypeCheckError();
      }
    }  
  }
  
  
  void genCode(){
    for( Iterator it = this.iterator(); it.hasNext(); ){
      Statement s = (Statement)it.next();
      s.genCode();
    }
  }

}
